###############################################################################
# $ID: docker-compose.yml, 13 Jan 2018 21:01, Leonid 'n3o' Knyazev $
###############################################################################
version: '3'

services:
  redis:
    build: ./data/services/redis
    restart: always
    env_file: .env
    ports:
      - "6379"

  mariadb:
    build: ./data/services/mariadb
    restart: always
    env_file: .env
    ports:
      - "3306"
    volumes:
      - ./storage/database:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    restart: always
    env_file: .env
    volumes:
      - .:/opt/app
    links:
      - redis
      - mariadb
    depends_on:
      - redis
      - mariadb
