###############################################################################
# $ID: docker-compose.yml, 13 Jan 2018 21:01, Leonid 'n3o' Knyazev $
###############################################################################
version: '2'

services:
  redis:
    container_name: bot-redis
    build: ./data/services/redis
    restart: always
    ports:
      - "6379"

  mariadb:
    container_name: bot-mariadb
    build: ./data/services/mariadb
    restart: always
    ports:
      - "3306"
    volumes:
      - ./storage/database:/var/lib/mysql
    environment:
      MYSQL_USER: geht
      MYSQL_PASSWORD: welovegeht
      MYSQL_DATABASE: discord
      MYSQL_ROOT_PASSWORD: root

  bot:
    container_name: bot
    build: .
    restart: always
    environment:
      BOT_ID: 396673027020029964
      BOT_NAME: GEHT Discord Bot
      BOT_TOKEN: Mzk2NjczMDI3MDIwMDI5OTY0.DSk2EA.Fus6uXnBBkkTyjbP1Re7IP_Okzs
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_CLIENT: mysql
      DB_HOST: mariadb
      DB_USER: geht
      DB_PASSWORD: welovegeht
      DB_DATABASE: discord
    links:
      - redis
      - mariadb
    depends_on:
      - redis
      - mariadb
