###############################################################################
# $ID: docker-compose.yml, 13 Jan 2018 21:01, Leonid 'n3o' Knyazev $
###############################################################################
version: '3'

services:
  redis:
    build: ./data/services/redis
    container_name: bot-redis
    restart: always
    env_file: .env
    ports:
      - "6379"

  mariadb:
    build: ./data/services/mariadb
    container_name: bot-mariadb
    restart: always
    env_file: .env
    ports:
      - "3306"
    volumes:
      - ./storage/database:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root

  bot:
    build: .
    container_name: bot
    restart: always
    env_file: .env
    links:
      - redis
      - mariadb
    depends_on:
      - redis
      - mariadb
