###############################################################################
# $ID: Dockerfile, 13 Jan 2018 21:01, Leonid 'n3o' Knyazev $
###############################################################################
FROM redis:latest

MAINTAINER Leonid Knyazev <leonid@knyazev.me>
